spring.application.name=cart-svc
server.port=8086

CATALOG_SVC_URL=${CATALOG_SVC_URL}
INVENTORY_SVC_URL=${INVENTORY_SVC_URL}
PROMOTIONS_SVC_URL=${PROMOTIONS_SVC_URL}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

resilience4j.circuitbreaker.instances.catalogSvc.sliding-window-size=10
resilience4j.circuitbreaker.instances.catalogSvc.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.catalogSvc.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.catalogSvc.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.catalogSvc.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.catalogSvc.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.inventorySvc.sliding-window-size=10
resilience4j.circuitbreaker.instances.inventorySvc.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.inventorySvc.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventorySvc.wait-duration-in-open-state=10s

management.endpoints.web.exposure.include=health,info,prometheus,circuitbreakers
management.endpoint.health.probes.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTLP_ENDPOINT:http://jaeger:4318/v1/traces}
