#!/usr/bin/env python3
"""
Operator credentials for Catalogix — the passwords YOU choose.

WHY THIS EXISTS
    Most secrets in Catalogix are machine secrets and stay randomly generated by
    Terraform (JWT signing key, per-service database roles). A few are credentials
    that a HUMAN types or shares, and those should be chosen by the person who
    deploys the app, not generated behind their back:

        db_master_password       RDS PostgreSQL master password
        rabbitmq_user/_password  RabbitMQ login (management UI + the services)
        seed_admin_password      the first application admin (see AdminSeeder)
        grafana_admin_user/_password
        db_readonly_username/_password   optional human read-only DB login

HOW IT REACHES EVERYTHING ELSE (no pipeline parameters are involved)
    This script writes ONE AWS Secrets Manager secret per environment:

        <cluster-name>/operator-credentials
        dev -> catalogix-cluster-dev/operator-credentials

    and everything else simply READS it from there:
      * platform-infra Terraform (on the Jenkins host)  -> db_master_password (+ optional read-only role)
      * External Secrets Operator                       -> rabbitmq_*, seed_admin_password -> pod env
                                                           grafana_admin_*                  -> Grafana
      * the pipelines                                   -> `--check` before doing anything

    Only the RDS master password has to pass through Terraform (and therefore state).
    The application admin, RabbitMQ and Grafana passwords never touch Terraform.

USAGE
    python credentials.py --env dev              # interactive: set / change credentials
    python credentials.py --env dev --show       # which keys exist (passwords are never printed)
    python credentials.py --env dev --check      # exit 1 unless every required key is present + valid
    python credentials.py --env dev --only seed_admin_password   # change just one
    python credentials.py --env dev --delete     # permanently delete this env's secret (confirms
                                                   # interactively; add --yes for non-interactive use)

    Re-run it any time to change a password. It only updates the secret:
      * app admin / RabbitMQ / Grafana: takes effect when the pods next read the secret
        (ESO refreshes hourly; `kubectl rollout restart` to apply immediately). NOTE the seeded admin
        is only created when no admin exists — to change an EXISTING admin's password use the
        Account page in the app. RabbitMQ only reads its credentials on first start with an empty
        data volume.
      * RDS master: re-run the platform-infra pipeline so Terraform applies the new password.

    DESTROY: this secret is created directly by this script (not by Terraform — see "HOW IT
    REACHES EVERYTHING ELSE" above for why it can't be), so a plain `terraform destroy` does not
    know it exists and will leave it behind. Jenkinsfile.platform-infra's destroy path runs
    `credentials.py --env <env> --delete --yes` right after `terraform destroy` succeeds, so one
    pipeline run tears down everything the environment owns. Doing a manual/non-Jenkins teardown?
    Run `--delete` yourself — nothing else will do it for you.

PASSWORD POLICY (the same rules are checked by Terraform and by the pipelines)
    8-64 characters, at least one lowercase, one uppercase and one digit, and none of
    / " @ or whitespace (RDS rejects those in a master password; the rest avoid quoting
    problems in URLs and shells). Use 12+ characters for anything reachable from the internet.

Standard library only, so it runs unchanged on your laptop and on the Jenkins host.
"""

import argparse
import getpass
import json
import os
import re
import secrets
import string
import subprocess
import sys
import tempfile

# Must equal CLUSTER_NAME in Jenkinsfile.app-cicd / Jenkinsfile.platform-infra
# (Terraform's local.env_prefix for each environment). dev and staging use DIFFERENT
# var.cluster_name defaults in Terraform (see env/*/variables.tf) — dev's is "catalogix-cluster",
# staging's is just "catalogix" — so the real env_prefix values are NOT parallel strings.
CLUSTER_NAMES = {
    "dev": "catalogix-cluster-dev",
    "staging": "catalogix-cluster-staging",
}

SECRET_SUFFIX = "operator-credentials"  # noqa: S105  # secret NAME, not password

MIN_LENGTH = 8
MAX_LENGTH = 64
FORBIDDEN_CHARS = '/"@'

USERNAME_RE = re.compile(r"^[a-z][a-z0-9_]{2,31}$")
GRAFANA_USER_RE = re.compile(r"^[A-Za-z0-9_.-]{3,32}$")


class Credential:
    def __init__(self, key, description, kind="password", required=True, default=None):
        self.key = key
        self.description = description
        self.kind = kind          # "password" | "username" | "grafana_user"
        self.required = required
        self.default = default

    @property
    def is_secret(self):
        return self.kind == "password"


CREDENTIALS = [
    Credential("db_master_password", "RDS PostgreSQL master password (user 'catalogix')"),
    Credential("rabbitmq_user", "RabbitMQ username", kind="username", default="catalogix"),
    Credential("rabbitmq_password", "RabbitMQ password"),
    Credential("seed_admin_password", "Password of the first app admin (admin@catalogix.local)"),
    Credential("grafana_admin_user", "Grafana admin username", kind="grafana_user", default="admin"),
    Credential("grafana_admin_password", "Grafana admin password"),
    Credential("db_readonly_username", "OPTIONAL read-only database login — username",
               kind="username", required=False, default="catalogix_readonly"),
    Credential("db_readonly_password", "OPTIONAL read-only database login — password (leave blank to skip)",
               required=False),
]


# --------------------------------------------------------------------------- validation

def password_problems(password):
    """Return a list of human-readable problems; empty means the password is acceptable."""
    problems = []
    if not isinstance(password, str):
        return ["must be text"]
    if not (MIN_LENGTH <= len(password) <= MAX_LENGTH):
        problems.append(f"must be {MIN_LENGTH}-{MAX_LENGTH} characters long")
    if not re.search(r"[a-z]", password):
        problems.append("needs at least one lowercase letter")
    if not re.search(r"[A-Z]", password):
        problems.append("needs at least one uppercase letter")
    if not re.search(r"[0-9]", password):
        problems.append("needs at least one digit")
    if any(c in password for c in FORBIDDEN_CHARS) or re.search(r"\s", password):
        problems.append('must not contain / " @ or whitespace')
    if not all(32 < ord(c) < 127 for c in password):
        problems.append("must use printable ASCII characters only")
    return problems


def username_problems(kind, value):
    pattern = GRAFANA_USER_RE if kind == "grafana_user" else USERNAME_RE
    if pattern.match(value or ""):
        return []
    if kind == "grafana_user":
        return ["3-32 characters: letters, digits, underscore, dot or hyphen"]
    return ["3-32 characters, start with a lowercase letter, then lowercase letters, digits or underscore"]


def value_problems(cred, value):
    return password_problems(value) if cred.is_secret else username_problems(cred.kind, value)


def generate_password(length=20):
    """A random password that satisfies the policy."""
    alphabet = string.ascii_letters + string.digits
    while True:
        candidate = "".join(secrets.choice(alphabet) for _ in range(length))
        if not password_problems(candidate):
            return candidate


# --------------------------------------------------------------------------- AWS access

class SecretNotFound(Exception):
    pass


def secret_id(env):
    return f"{CLUSTER_NAMES[env]}/{SECRET_SUFFIX}"


def _aws(args, region):
    cmd = ["aws", "secretsmanager", *args]
    if region:
        cmd += ["--region", region]
    return subprocess.run(cmd, capture_output=True, text=True)


def fetch_secret(env, region):
    """Return the current secret as a dict, or raise SecretNotFound."""
    result = _aws(["get-secret-value", "--secret-id", secret_id(env),
                   "--query", "SecretString", "--output", "text"], region)
    if result.returncode != 0:
        if "ResourceNotFoundException" in result.stderr:
            raise SecretNotFound(secret_id(env))
        raise RuntimeError(f"aws secretsmanager get-secret-value failed: {result.stderr.strip()}")
    return json.loads(result.stdout)


def store_secret(env, region, values, exists):
    """Write the secret. The JSON goes through a 0600 temp file (file://), never the command line,
    so passwords are not visible in the process list."""
    fd, path = tempfile.mkstemp(prefix="catalogix-cred-", suffix=".json")
    try:
        os.chmod(path, 0o600)
        with os.fdopen(fd, "w") as fh:
            json.dump(values, fh)
        if exists:
            args = ["put-secret-value", "--secret-id", secret_id(env), "--secret-string", f"file://{path}"]
        else:
            args = ["create-secret", "--name", secret_id(env), "--secret-string", f"file://{path}",
                    "--description", "Operator-chosen credentials for Catalogix (scripts/python/credentials.py)"]
        result = _aws(args, region)
        if result.returncode != 0:
            raise RuntimeError(f"aws secretsmanager write failed: {result.stderr.strip()}")
    finally:
        try:
            os.remove(path)
        except OSError:
            pass


# --------------------------------------------------------------------------- check / show

def check_values(values):
    """Problems with a stored secret (missing required keys, policy violations)."""
    problems = []
    for cred in CREDENTIALS:
        value = values.get(cred.key)
        if value in (None, ""):
            if cred.required:
                problems.append(f"{cred.key}: missing")
            continue
        for p in value_problems(cred, value):
            problems.append(f"{cred.key}: {p}")
    # A read-only login needs both halves.
    if bool(values.get("db_readonly_password")) and not values.get("db_readonly_username"):
        problems.append("db_readonly_username: required when db_readonly_password is set")
    return problems


def cmd_check(env, region):
    try:
        values = fetch_secret(env, region)
    except SecretNotFound:
        print(f"ERROR: {secret_id(env)} does not exist. Run:  python scripts/python/credentials.py --env {env}")
        return 1
    problems = check_values(values)
    if problems:
        print(f"ERROR: {secret_id(env)} is incomplete or invalid:")
        for p in problems:
            print(f"  - {p}")
        print(f"Fix with:  python scripts/python/credentials.py --env {env}")
        return 1
    print(f"OK: {secret_id(env)} has every required credential and they meet the password policy.")
    return 0


def cmd_show(env, region):
    try:
        values = fetch_secret(env, region)
    except SecretNotFound:
        print(f"{secret_id(env)} does not exist yet. Run without --show to create it.")
        return 1
    print(f"{secret_id(env)}")
    for cred in CREDENTIALS:
        value = values.get(cred.key)
        if value in (None, ""):
            state = "MISSING" if cred.required else "not set (optional)"
        elif cred.is_secret:
            state = "set (hidden)"
        else:
            state = f"set: {value}"
        print(f"  {cred.key:24s} {state}")
    return 0


# --------------------------------------------------------------------------- interactive

def _prompt_secret(cred, have):
    hint = " — Enter keeps the current value" if have else ""
    if not cred.required:
        hint += " — Enter to skip"
    while True:
        first = getpass.getpass(f"  {cred.description}{hint}\n  (type g to generate one) > ")
        if first == "":
            if have or not cred.required:
                return None
            print("    This one is required.")
            continue
        if first.lower() == "g":
            generated = generate_password()
            print(f"    Generated: {generated}   <- shown once; it is stored in Secrets Manager")
            return generated
        problems = password_problems(first)
        if problems:
            print("    Not accepted: " + "; ".join(problems))
            continue
        if getpass.getpass("  Repeat it > ") != first:
            print("    The two entries differ — try again.")
            continue
        return first


def _prompt_text(cred, current):
    default = current or cred.default
    while True:
        answer = input(f"  {cred.description} [{default}] > ").strip() or default
        problems = username_problems(cred.kind, answer)
        if not problems:
            return answer
        print("    Not accepted: " + "; ".join(problems))


def interactive(env, region, only=None):
    try:
        values, exists = fetch_secret(env, region), True
    except SecretNotFound:
        values, exists = {}, False

    print(f"\nCredentials for '{env}' -> {secret_id(env)}")
    print(f"Password rule: {MIN_LENGTH}-{MAX_LENGTH} chars, upper + lower + digit, no / \" @ or spaces "
          f"(12+ recommended).\n")

    wanted = [c for c in CREDENTIALS if only is None or c.key in only]
    if only and len(wanted) != len(set(only)):
        unknown = set(only) - {c.key for c in CREDENTIALS}
        print(f"ERROR: unknown key(s): {', '.join(sorted(unknown))}")
        return 1

    changed = {}
    skip_readonly = False
    for cred in wanted:
        if cred.key.startswith("db_readonly") and only is None and not exists and not skip_readonly:
            answer = input(
                "Create a read-only database login for looking at data with psql/pgAdmin? (y/N) "
            ).strip().lower()
            skip_readonly = answer not in ("y", "yes")
        if cred.key.startswith("db_readonly") and skip_readonly:
            continue
        if cred.is_secret:
            new = _prompt_secret(cred, have=bool(values.get(cred.key)))
        else:
            new = _prompt_text(cred, values.get(cred.key))
        if new is not None and new != values.get(cred.key):
            changed[cred.key] = new

    if not changed:
        print("\nNothing changed.")
        return cmd_check(env, region) if exists else 1

    merged = {**values, **changed}
    problems = check_values(merged) if only is None else []
    if problems:
        print("\nNot saved — still incomplete:")
        for p in problems:
            print(f"  - {p}")
        return 1

    store_secret(env, region, merged, exists)
    print(f"\nSaved {len(changed)} value(s) to {secret_id(env)}: {', '.join(sorted(changed))}")
    print("Next: run the platform-infra pipeline (Terraform reads db_master_password from here).")
    if "seed_admin_password" in changed and exists:
        print("Note: an admin that already exists keeps its current password — change it on the Account page.")
    return 0


# --------------------------------------------------------------------------- entry point

def resolve_region(cli_region):
    if cli_region:
        return cli_region
    for var in ("AWS_REGION", "AWS_DEFAULT_REGION"):
        if os.environ.get(var):
            return os.environ[var]
    result = subprocess.run(["aws", "configure", "get", "region"], capture_output=True, text=True)
    return result.stdout.strip() or None


def cmd_delete(env, region, assume_yes):
    """Permanently delete the operator-credentials secret for one environment.

    This is the counterpart to the gap a plain `terraform destroy` has: platform-infra's
    Terraform never created this secret (see the module docstring at the top of this file for
    why it can't — the RDS master password must exist here BEFORE Terraform's first apply, so
    Terraform can't be the one to create the container), so `terraform destroy` has no idea it
    exists and always leaves it behind. Jenkinsfile.platform-infra's destroy path calls this
    (`--yes`, non-interactive) right after `terraform apply destroy.tfplan` succeeds, so "destroy
    everything" for an environment is one pipeline run, not a pipeline run plus a manual step
    someone has to remember. Run it by hand for a destroy done outside Jenkins.
    """
    sid = secret_id(env)
    try:
        fetch_secret(env, region)
    except SecretNotFound:
        print(f"{sid} does not exist — nothing to delete.")
        return 0

    if not assume_yes:
        answer = input(f"Permanently delete {sid}? This cannot be undone. Type 'yes' to confirm: ").strip()
        if answer != "yes":
            print("Not deleted.")
            return 1

    result = _aws(["delete-secret", "--secret-id", sid, "--force-delete-without-recovery"], region)
    if result.returncode != 0:
        print(f"ERROR: could not delete {sid}: {result.stderr.strip()}")
        return 1
    print(f"Deleted {sid}.")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description="Set the operator-chosen credentials for a Catalogix environment.")
    parser.add_argument("--env", choices=sorted(CLUSTER_NAMES), required=True)
    parser.add_argument("--region", help="AWS region (default: AWS_REGION, then `aws configure`)")
    parser.add_argument("--check", action="store_true", help="validate only; exit 1 if anything is missing or invalid")
    parser.add_argument("--show", action="store_true", help="list which keys are set (never prints passwords)")
    parser.add_argument("--only", nargs="+", metavar="KEY", help="change only these keys")
    parser.add_argument("--delete", action="store_true",
                         help="permanently delete this environment's operator-credentials secret "
                              "(the cleanup terraform destroy can't do — see cmd_delete)")
    parser.add_argument("--yes", action="store_true",
                         help="with --delete, skip the confirmation prompt (for non-interactive/CI use)")
    args = parser.parse_args(argv)

    region = resolve_region(args.region)
    if not region:
        print("ERROR: no AWS region — pass --region or set AWS_REGION.")
        return 2
    if args.delete:
        return cmd_delete(args.env, region, args.yes)
    if args.check:
        return cmd_check(args.env, region)
    if args.show:
        return cmd_show(args.env, region)
    return interactive(args.env, region, only=args.only)


if __name__ == "__main__":
    sys.exit(main())
