#!/usr/bin/env python3
"""
new-service.py — golden-path scaffolding for a new Catalogix backend service.

Usage: python3 scripts/platform/new-service.py <service-name> <port>
Example: python3 scripts/platform/new-service.py shipping-svc 11010

What this wires the new service into automatically (the whole point of a
golden path — this is the exact list of places a 9-to-10 service change
touches by hand today, per the Helm/Terraform/Jenkins work done in this
project's upgrade):
  1. backend/<svc>/pom.xml, Dockerfile, a minimal Spring Boot skeleton
  2. Root pom.xml — adds the new <module>
  3. helm/catalogix-hc/values-dev.yaml + values-staging.yaml — adds a
     services: entry (routeToALB: false by default — a NEW service
     shouldn't be internet-routed until someone deliberately opts it in,
     safer default than the reverse)
  4. terraform/platform-infra/env/{dev,staging}/main.tf — adds the service
     to db_roles.services (gets its own database + role automatically)
     AND to module.ecr's repositories list
  5. Jenkinsfile.app-cicd — adds the service to BACKEND_SERVICES
  6. catalog-info.yaml — adds a Component entity

What this deliberately does NOT do — real business logic, actual API
design, writing tests, or running `terraform apply`/`helm upgrade`. This
generates a scaffold that compiles and deploys as an empty shell; it does
not generate a service, it removes everything except the actual feature
work.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def derive_names(service_name: str) -> dict:
    if not re.fullmatch(r"[a-z][a-z0-9-]*-svc", service_name):
        sys.exit(f"Service name must look like 'something-svc' (lowercase, hyphenated). Got: {service_name}")
    pkg = service_name.replace("-svc", "").replace("-", "")
    class_prefix = "".join(w.capitalize() for w in service_name.replace("-svc", "").split("-"))
    db_name = f"catalogix_{service_name.replace('-svc', '').replace('-', '_')}"
    return {
        "svc": service_name,
        "pkg": pkg,
        "class_prefix": class_prefix,
        "db_name": db_name,
    }


def write_pom(svc_dir: Path, names: dict):
    pom = f'''<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.catalogix</groupId>
    <artifactId>catalogix</artifactId>
    <version>1.0</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <artifactId>{names['svc']}</artifactId>
  <version>1.0</version>
  <packaging>jar</packaging>

  <properties>
    <maven.compiler.release>${{java.version}}</maven.compiler.release>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-prometheus</artifactId>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-database-postgresql</artifactId>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <finalName>{names['svc']}</finalName>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
'''
    (svc_dir / "pom.xml").write_text(pom)


def write_dockerfile(svc_dir: Path, names: dict, port: int):
    svc = names["svc"]
    dockerfile = f'''# Multi-stage Dockerfile for {svc} — generated by scripts/platform/new-service.py,
# matches every other service's Dockerfile shape exactly.
FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
WORKDIR /app

COPY pom.xml ./pom.xml
RUN mvn -B -N install

COPY backend/{svc}/pom.xml {svc}/pom.xml
COPY backend/{svc}/src {svc}/src
RUN mvn -B clean package -DskipTests -f {svc}/pom.xml

FROM gcr.io/distroless/java21-debian13:nonroot AS app
WORKDIR /app

COPY --from=build /app/{svc}/target/{svc}.jar {svc}.jar
EXPOSE {port}

ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75", "-XX:InitialRAMPercentage=50", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app/{svc}.jar"]
'''
    (svc_dir / "Dockerfile").write_text(dockerfile)


def write_java_skeleton(svc_dir: Path, names: dict, port: int):
    pkg, class_prefix, svc = names["pkg"], names["class_prefix"], names["svc"]
    java_dir = svc_dir / "src" / "main" / "java" / "com" / "catalogix" / pkg
    java_dir.mkdir(parents=True, exist_ok=True)

    app_java = f'''package com.catalogix.{pkg};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class {class_prefix}Application {{
    public static void main(String[] args) {{
        SpringApplication.run({class_prefix}Application.class, args);
    }}
}}
'''
    (java_dir / f"{class_prefix}Application.java").write_text(app_java)

    resources_dir = svc_dir / "src" / "main" / "resources"
    resources_dir.mkdir(parents=True, exist_ok=True)
    props = f'''spring.application.name={svc}
server.port={port}

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.probes.enabled=true

# JWT_SECRET is read directly from the environment via @Value("${{JWT_SECRET}}")
# — must be set (see helm/catalogix-hc's commonEnv helper / docker-compose.yaml).

spring.flyway.locations=classpath:db/migration
'''
    (resources_dir / "application.properties").write_text(props)

    migration_dir = resources_dir / "db" / "migration"
    migration_dir.mkdir(parents=True, exist_ok=True)
    (migration_dir / "V1__init.sql").write_text(
        f"-- {svc} starts with no tables. Add your first real migration here.\n"
    )

    test_dir = svc_dir / "src" / "test" / "java" / "com" / "catalogix" / pkg
    test_dir.mkdir(parents=True, exist_ok=True)


def add_maven_module(names: dict) -> bool:
    pom_path = REPO_ROOT / "pom.xml"
    content = pom_path.read_text()
    new_module = f"        <module>backend/{names['svc']}</module>"
    if new_module in content:
        return False
    content = content.replace("    </modules>", f"{new_module}\n    </modules>")
    pom_path.write_text(content)
    return True


def add_helm_values(names: dict, port: int) -> list:
    touched = []
    entry = f'''
  {names['svc']}:
    dbName: {names['db_name']}
    image: {{ repository: "{names['svc']}", pullPolicy: "IfNotPresent" }}
    port: {port}
    replicaCount: 2
    # Safer default for a brand-new service: NOT internet-routed until
    # someone deliberately opts it in (flip to true + set ingressPath).
    routeToALB: false
    resources:
      requests: {{ cpu: "100m", memory: "128Mi" }}
      limits: {{ cpu: "400m", memory: "384Mi" }}
    hpa: {{ minReplicas: 2, maxReplicas: 4, cpuUtilization: 75, memoryUtilization: 75 }}
    extraEnv: []
'''
    for fname in ("values-dev.yaml", "values-staging.yaml"):
        path = REPO_ROOT / "helm" / "catalogix-hc" / fname
        content = path.read_text()
        if f"\n  {names['svc']}:\n" in content:
            continue
        content = content.replace("\nfrontendSvc:", f"{entry}\nfrontendSvc:")
        path.write_text(content)
        touched.append(str(path.relative_to(REPO_ROOT)))
    return touched


def add_terraform_entries(names: dict) -> list:
    touched = []
    for env in ("dev", "staging"):
        main_path = REPO_ROOT / "terraform" / "platform-infra" / "env" / env / "main.tf"
        content = main_path.read_text()

        db_role_line = f'    "{names["svc"]}"      = "{names["db_name"]}"'
        if db_role_line not in content:
            anchor = '    "review-svc"       = "catalogix_reviews"\n'
            if anchor not in content:
                raise RuntimeError(f'Could not find db_roles anchor in {main_path}')
            content = content.replace(anchor, anchor + db_role_line + "\n", 1)
            main_path.write_text(content)
            touched.append(str(main_path.relative_to(REPO_ROOT)))

    ecr_path = REPO_ROOT / "terraform" / "platform-infra" / "env" / "dev" / "main.tf"
    content = ecr_path.read_text()
    ecr_block = content.split('module "ecr"', 1)[1].split(']', 1)[0]
    if f'"{names["svc"]}"' not in ecr_block:
        anchor = '    "frontend-svc"'
        if anchor not in content:
            raise RuntimeError(f'Could not find ECR service anchor in {ecr_path}')
        content = content.replace(anchor, f'{anchor}, "{names["svc"]}"', 1)
        ecr_path.write_text(content)
        if str(ecr_path.relative_to(REPO_ROOT)) not in touched:
            touched.append(str(ecr_path.relative_to(REPO_ROOT)))
    return touched

def add_catalog_entry(names: dict) -> bool:
    path = REPO_ROOT / "catalog-info.yaml"
    content = path.read_text()
    if f"name: {names['svc']}\n" in content:
        return False
    entry = f'''
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {names['svc']}
  description: TODO — describe what this service does.
  tags: [java, spring-boot, backend]
spec:
  type: service
  lifecycle: experimental
  owner: group:platform-team
  system: catalogix
  dependsOn:
    - resource:catalogix-postgres
'''
    path.write_text(content.rstrip("\n") + "\n" + entry)
    return True


def main():
    if len(sys.argv) != 3:
        sys.exit(f"Usage: {sys.argv[0]} <service-name> <port>")
    service_name, port = sys.argv[1], int(sys.argv[2])
    names = derive_names(service_name)

    svc_dir = REPO_ROOT / "backend" / names["svc"]
    if svc_dir.exists():
        sys.exit(f"backend/{names['svc']} already exists — refusing to overwrite.")
    svc_dir.mkdir(parents=True)

    write_pom(svc_dir, names)
    write_dockerfile(svc_dir, names, port)
    write_java_skeleton(svc_dir, names, port)

    changes = []
    if add_maven_module(names):
        changes.append("pom.xml (added module)")
    changes += [f"{f} (added services: entry)" for f in add_helm_values(names, port)]
    changes += [f"{f} (added db-role + ECR entry)" for f in add_terraform_entries(names)]
    if add_jenkins_entry(names):
        changes.append("Jenkinsfile.app-cicd (added to BACKEND_SERVICES)")
    if add_catalog_entry(names):
        changes.append("catalog-info.yaml (added Component)")

    print(f"\nScaffolded backend/{names['svc']} on port {port}, database {names['db_name']}.\n")
    print("Wired into:")
    for c in changes:
        print(f"  - {c}")
    print("\nSTILL YOUR JOB (this is a golden path, not a finished service):")
    print("  - Actual business logic, entities, controllers, real migrations")
    print("  - Tests (unit + integration where appropriate)")
    print("  - Deciding routeToALB — currently false (internal-only) by default")
    print("  - terraform apply / helm upgrade to actually provision the DB role + deploy")


if __name__ == "__main__":
    main()
