{{- range $name, $svc := .Values.services }}
{{- if or (and $.Values.hpa $.Values.hpa.enabled) (gt ($svc.replicaCount | int) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}-pdb
  namespace: {{ $.Release.Namespace }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ $name }}
---
{{- end }}
{{- end }}
{{- if or (and .Values.hpa .Values.hpa.enabled) (gt (.Values.frontendSvc.replicaCount | int) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-svc-pdb
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend-svc
{{- end }}
---
{{- if or (and .Values.gateway.hpa .Values.gateway.hpa.enabled) (gt (.Values.gateway.replicaCount | int) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-pdb
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: gateway
{{- end }}
