apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalogix-monitoring.fullname" . }}-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Release.Name }}-kube-prometheus-stack-prometheus:9090
        isDefault: true
        editable: false
