plugins:
  - artifactId: docker-workflow

  # CORE
  - artifactId: configuration-as-code
  - artifactId: matrix-auth
  - artifactId: credentials
  - artifactId: credentials-binding

  # PIPELINES
  - artifactId: workflow-aggregator
  - artifactId: pipeline-graph-view

  # SCM
  - artifactId: git
  - artifactId: github

  # JOB DSL
  - artifactId: job-dsl

  # TOOLS
  - artifactId: nodejs
  - artifactId: maven-plugin

  # SONAR
  - artifactId: sonar

  # AWS
  - artifactId: aws-credentials

  # UTILS
  - artifactId: timestamper
  - artifactId: ws-cleanup
  - artifactId: dark-theme