apiVersion: v2
name: catalogix-hc
description: Catalogix — 7-service microservices app (user/catalog/inventory/cart/payment/checkout/notification) + frontend + in-cluster RabbitMQ, using an AWS ALB -> in-cluster nginx gateway edge
type: application
version: 0.2.0
appVersion: "2.0"
